spring:
  data:
    mongodb:
      uri: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      database: JournalEntry
      auto-index-creation: true


server:
  port: 9090
