spring:
  data:
    mongodb:
      uri: mongodb+srv://karanabhinav2002:1SMXt1I18au69mcG@journal.uimjroa.mongodb.net/?retryWrites=true&w=majority&appName=Journal
      database: JournalEntry
      auto-index-creation: true


server:
  port: 9090